# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit clarify.Rmd to modify this file

## ----setup,include=FALSE--------------------------------------------------------------------------------------------
knitr::opts_chunk$set(
  fig.path = "figures/",
  fig.align='center',
  fig.height = 2
)

if (!requireNamespace("clarify")) {
  install.packages("clarify")
}

if (!requireNamespace("MatchIt")) {
  install.packages("MatchIt")
}

if (!requireNamespace("Amelia")) {
  install.packages("Amelia")
}


## ----library--------------------------------------------------------------------------------------------------------
library(clarify)


## ----data-----------------------------------------------------------------------------------------------------------
data("lalonde", package = "MatchIt")

# Create a binary outcome variable
lalonde$re78_0 <- ifelse(lalonde$re78 > 0, 1, 0)

head(lalonde)


## ----fit------------------------------------------------------------------------------------------------------------
fit <- glm(re78_0 ~ treat * married + age + educ + race +
             nodegree + re74 + re75, data = lalonde,
           family = binomial("probit"))


## ----sim------------------------------------------------------------------------------------------------------------
set.seed(1234)

# Drawing 1000 simulated coefficients using an HC2 robust
# covariance matrix
s <- sim(fit, n = 1000,
         vcov = "HC2")

s


## ----sim_fun1-------------------------------------------------------------------------------------------------------
sim_fun1 <- function(fit) {
  predict(fit, newdata = lalonde["PSID1",], type = "response")
}


## ----est1-----------------------------------------------------------------------------------------------------------
est1 <- sim_apply(s, FUN = sim_fun1, verbose = FALSE)

est1


## ----sim_fun2-------------------------------------------------------------------------------------------------------
sim_fun2 <- function(coefs) {
  hispan <- unname(coefs["racehispan"])
  white <- unname(coefs["racewhite"])
  
  c("w - h" = white - hispan)
}

est2 <- sim_apply(s, FUN = sim_fun2, verbose = FALSE)

est2


## ----plot1, fig.width=4---------------------------------------------------------------------------------------------
plot(est1, reference = TRUE, ci = FALSE)


## ----summary1-------------------------------------------------------------------------------------------------------
summary(est1)


## ----plot2, fig.width=4---------------------------------------------------------------------------------------------
plot(est2, reference = TRUE, ci = FALSE)

summary(est2, method = "wald", null = 0)


## ----setx3----------------------------------------------------------------------------------------------------------
est3 <- sim_setx(s,
                 x = list(treat = 0:1,
                          re75 = c(0, 20000),
                          race = "black"),
                 verbose = FALSE)


## ----summary3-------------------------------------------------------------------------------------------------------
summary(est3)


## ----attr3----------------------------------------------------------------------------------------------------------
attr(est3, "setx")


## ----plot3, fig.width=5---------------------------------------------------------------------------------------------
plot(est3, var = "re75", ci = FALSE)


## ----setx4----------------------------------------------------------------------------------------------------------
est4 <- sim_setx(s,
                 x = list(treat = 0:1,
                          re75 = seq(0, 20000, by = 2000),
                          race = "black"),
                 verbose = FALSE)


## ----plot4, fig.width=5---------------------------------------------------------------------------------------------
plot(est4)


## ----setx5----------------------------------------------------------------------------------------------------------
est5 <- sim_setx(s,
                 x = list(treat = 0, re75 = 0),
                 x1 = list(treat = 1, re75 = 0),
                 verbose = FALSE)


## ----summary5-------------------------------------------------------------------------------------------------------
summary(est5)


## ----ame6-----------------------------------------------------------------------------------------------------------
est6 <- sim_ame(s,
                var = "treat",
                subset = treat == 1,
                contrast = "rr",
                verbose = FALSE)


## ----summary6-------------------------------------------------------------------------------------------------------
summary(est6, null = c(`RR` = 1))


## ----ame7-----------------------------------------------------------------------------------------------------------
est7 <- sim_ame(s,
                var = "age",
                verbose = FALSE)


## ----summary7-------------------------------------------------------------------------------------------------------
summary(est7)


## ----ame6b----------------------------------------------------------------------------------------------------------
est6b <- sim_ame(s,
                 var = "treat",
                 subset = treat == 1,
                 by = ~married,
                 contrast = "rr",
                 verbose = FALSE)

summary(est6b)


## ----adrf8----------------------------------------------------------------------------------------------------------
age_seq <- seq(18, 50, by = 2)

est8 <- sim_adrf(s,
                 var = "age",
                 contrast = "adrf",
                 at = age_seq,
                 verbose = FALSE)


## ----plot8, fig.width=5---------------------------------------------------------------------------------------------
plot(est8)


## ----summary8-------------------------------------------------------------------------------------------------------
summary(est8, parm = 1:4)


## ----adrf9----------------------------------------------------------------------------------------------------------
est9 <- sim_adrf(s,
                 var = "age",
                 contrast = "amef",
                 at = age_seq,
                 verbose = FALSE)


## ----plot9, fig.width=5---------------------------------------------------------------------------------------------
plot(est9)


## ----transform_demo-------------------------------------------------------------------------------------------------
lalonde <- transform(lalonde,
                     re78_0 = ifelse(re78 == 0, 1, 0))


## ----transform6-----------------------------------------------------------------------------------------------------
est6 <- transform(est6,
                  RD = `E[Y(1)]` - `E[Y(0)]`)


## ----transform6b, eval = FALSE--------------------------------------------------------------------------------------
#> est6 <- transform(est6,
#>                   RD = .b2 - .b1)


## ----summary6_transform---------------------------------------------------------------------------------------------
summary(est6, null = c(`RR` = 1, `RD` = 0))


## ----summary6b_transform--------------------------------------------------------------------------------------------
est6b |>
  transform(`RR[1]/RR[0]` = `RR[1]` / `RR[0]`) |>
  summary(parm = c("RR[0]", "RR[1]", "RR[1]/RR[0]"),
          null = 1)


## ----ame_by_race----------------------------------------------------------------------------------------------------
# AME of treat with race = "black"
est10b <- sim_ame(s, var = "treat", subset = race == "black",
                  contrast = "diff", verbose = FALSE)
summary(est10b)

# AME of treat with race = "hispan"
est10h <- sim_ame(s, var = "treat", subset = race == "hispan",
                  contrast = "diff", verbose = FALSE)
summary(est10h)


## ----names----------------------------------------------------------------------------------------------------------
names(est10b) <- paste(names(est10b), "b", sep = "_")
names(est10h) <- paste(names(est10h), "h", sep = "_")


## ----cbind10--------------------------------------------------------------------------------------------------------
est10 <- cbind(est10b, est10h)
summary(est10)


## ----summary10------------------------------------------------------------------------------------------------------
est10 <- transform(est10,
                   `Dh - Db` = Diff_h - Diff_b)
summary(est10, parm = "Dh - Db")


## ----amelia_load, include=F-----------------------------------------------------------------------------------------
amelia_ok <- requireNamespace("Amelia", quietly = TRUE)
knitr::opts_chunk$set(
  eval = amelia_ok
)
if (amelia_ok) library(Amelia)


## ----misim, message=F-----------------------------------------------------------------------------------------------
library(Amelia)
data("africa", package = "Amelia")

# Multiple imputation
a.out <- amelia(x = africa, m = 10, cs = "country",
                ts = "year", logs = "gdp_pc", p2s = 0)

# Fit model to each dataset
model.list <- with(a.out, lm(gdp_pc ~ infl * trade))

# Simulate coefficients, 100 draws per imputation
si <- misim(model.list, n = 100)

si


## ----esi_mi---------------------------------------------------------------------------------------------------------
sim_fun <- function(fit) {
  #Extract the original dataset using get_predictors()
  X <- insight::get_predictors(fit)
  
  p0 <- predict(fit)
  
  #Predictions after perturbing infl slightly
  p1 <- predict(fit, newdata = transform(X, infl = infl + 1e-5))
  
 c(AME = mean((p1 - p0) / 1e-5))
}

est_mi <- sim_apply(si, FUN = sim_fun, verbose = FALSE)

summary(est_mi)


## ----est_mi2--------------------------------------------------------------------------------------------------------
est_mi2 <- sim_ame(si, var = "infl", verbose = FALSE)

summary(est_mi2)

